### ISSUE TITLE
gsync-webrtc fails, should add wiki for ssh key 

### ISSUE THREAD

**Issue by iddoeldor** [signalapp/ringrtc#14]

**Comment by jim-signal** [comment]
Hi @iddoeldor, I suppose you are seeing an issue when running `make`? It seems that we have relied on there being a configured GitHub SSH key already setup. This can be fixed by making the following change:

File: config/webrtc.gclient.common
Line: 10

Change the `"url"` value to be: `"https://github.com/signalapp/webrtc.git"`

All dependencies needed to build RingRTC are public, so no SSH keys should be necessary. I think we will make this change for future releases.

BTW, what platform are you building for?

**Comment by iddoeldor** [comment]
Unix x64, thank you. Will update.
