### ISSUE TITLE
Samsung A3 (2017) video freezes when switching camera

### ISSUE THREAD

**Issue by aleb2000** [signalapp/ringrtc#16]
When in a video call with a Samsung Galaxy A3 (2017) the video freezes when the caller switches the camera.

The same problem was solved for Samsung S7 with this commit: https://github.com/signalapp/ringrtc/commit/0072a9e6ea533c03479d663bac101208f18d294c

Samsung Galaxy A3 (2017)'s model number: SM-A320FL

**Comment by jim-signal** [comment]
Hi @aleb2000, thanks for the report! Yes, this looks like another Exynos device that has longevity issues with the hardware encoder. We will add it to the mentioned list to force it to use the software encoder. I am not sure how long it will take to get in to the client release though, so keep a watch for it and please close this when the issue is resolved.

**Comment by aleb2000** [comment]
Fixed with commit https://github.com/signalapp/ringrtc/commit/f4c90be7c43e4f9ec98b53c7110924f546da7d02 included in Signal Android 4.78.3.
Thank you for the immediate reply and the quick fix.
