### ISSUE TITLE
Opus audio quality poor for music

### ISSUE THREAD

**Issue by onny** [signalapp/ringrtc#24]
Hey,
for testing and experimentation purpose I wanted to see how could audio quality is in case of streaming music or similar non-speech audio. I tried to set higher bitrates / max_bitrates in ``src/rust/src/webrtc/media.rs b/src/rust/src/webrtc/media.rs`` but the sound quality was still choppy and "metallic".
Is it possible in the future to have better audio quality in Signal for such use cases?

Best regards
Jonas

**Comment by jim-signal** [comment]
Hi @onny, if you are experimenting, you could try to modify this line https://github.com/signalapp/ringrtc-private/blob/830779be6e7297713d2ff8ae49ff41f5ca4e20e1/src/rust/src/core/bandwidth_mode.rs#L84 and set a value of 128_000 for all bitrates (as per the opus rfc).

You would need to do this on all clients you want to test with since these bitrates are not negotiated. This might help. However, the current design of audio for Signal clients is focused on speech and you may run in to other issues such as stereo (most of it expects a mono input signal) and jitter settings (if you wanted to stream music, a slightly longer buffer would be helpful to eliminate choppy sounds in bad network conditions).

As for adding this as a feature, maybe commenting in the community forum (https://community.signalusers.org/) may help, but we'll also keep it in mind!

**Comment by onny** [comment]
Thanks for the feedback :) I changed them already to 65_000 but that maybe wasn't enough.
Oh I thought changing this on the sender side is enough to transmit higher audio signals? I'll give it a try with patched clients too :+1:
