### ISSUE TITLE
Precompiled ringrtc for swift 5.1.0

### ISSUE THREAD

**Issue by zykis** [signalapp/ringrtc#3]
Hey guys! Do you have a precompiled RingRTC for swift 5.1.0?
Kinda want to use it for iOS 13.0, but compiling by myself seems to have an issues due to dependencies

**Comment by jim-signal** [comment]
Hi there. We don't have any precompiled libraries for Swift 5.1, since we're not using that internally yet. As you may know, the artifacts we do have are in [signal-webrtc-ios-artifacts](https://github.com/signalapp/signal-webrtc-ios-artifacts). 

If you can share some information for the dependencies that are problematic, we might be able to offer a suggestion.

**Comment by zykis** [comment]
I've just wanted to compile Signal for iOS 13.0. 
Used Xcode 10.3 with swift 5.0.1 for that purposes in conjunction with Device Support importing from Xcode 11.0.
Fixed all crashes from WebRTC calls for iOS 13. Works like a charm.

**Comment by jim-signal** [comment]
That's great @zykis! Thanks for the information. If you have any suggestions/feedback about the crashes you saw and how to fix them, please do share.

I will close this issue now.
