### ISSUE TITLE
do not assume a build's purpose based on its target architecture

### ISSUE THREAD

**Issue by brjsp** [signalapp/ringrtc#57]
commit be737c39d5b03dfadb7db61d0e234c55d8c755a8 removes some features on linux aarch64 (and only aarch64), i'm assuming because they are only used by the electron app.

I maintain the signal-desktop package in openSUSE. in addition to x86_64, we also provide aarch64, armhf and riscv64 versions. We'd like to keep the application fully-functional across all architectures.

If you need to build a version of ringrtc with some functionality disabled in your CI, please cleanly delineate it as a cargo feature instead of making such assumptions.

**Comment by mutexlox-signal** [comment]
The problem that be737c3 is trying to fix is that we have a dep that was failing to build on aarch64 linux (see https://github.com/mozilla/cubeb-rs/pull/97).

This is a short-term workaround to avoid breaking the build until that dep is fixed and the fix is pushed to crates.io; we do want to build this feature for aarch64 linux once that's done.

**Comment by mutexlox-signal** [comment]
BTW, thanks for your work on maintaining the package for openSUSE :)

**Comment by mutexlox-signal** [comment]
Fixed in the just-published 2.48.6.

**Comment by mkurz** [comment]
I suspect something is still wrong, see
- #59
